DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS books;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author TEXT NOT NULL,
  published INTEGER NOT NULL,
  publisher TEXT NOT NULL,
  title TEXT NOT NULL
);